FinanSmart.WebApp/Controllers/AutenticacaoController.cs
using FinanSmart.Dominio.Interface.Serviços;
using FinanSmart.Dominio.ValueObjects;
using FinanSmart.WebApp.Models;
using Microsoft.AspNetCore.Mvc;

public class AutenticacaoController : Controller
{
    ICadastroService _service;
    public AutenticacaoController(ICadastroService service) { _service = service; }

    [HttpGet]
    public IActionResult Index()
    {
        if (HttpContext.Session.GetString("Usuario") != null)
            return RedirectToAction("Index", "Home");

        return View(new CadastroModel());
    }

    [HttpPost]
    public IActionResult Autenticar(UsuarioViewModel entidade)
    {
        if (true)
            return base.RedirectToAction("Index", "Home");
        else
            return base.RedirectToAction("Erro");
    }

    public IActionResult Cadastrar (CadastroModel Cadastro) {

        Cadastro cad = new()
        {
            CPF = Cadastro.CPF,
            PrimeiroNome = Cadastro.PrimeiroNome,
            Sobrenome = Cadastro.Sobrenome,
            Senha = Cadastro.Senha,
            Email = Cadastro.Email
        };

        _service.AdicionarCadastro(cad);
        return RedirectToAction("Index", "Autenticado");
    }

    [HttpGet]
    public IActionResult Erro()
    {
        return View();
    }
}

FinanSmart.WebApp/Controllers/CadastrosController.cs
using FinanSmart.Dominio.Interface.Repository;
using FinanSmart.Dominio.ValueObjects;
using Microsoft.AspNetCore.Mvc;

namespace FinanSmart.WebApp.Controllers
{
    public class CadastrosController : Controller
    {
        private readonly ICadastroRepository _cadastroRepository;
        public CadastrosController(ICadastroRepository cadastroRepository)
        {
            _cadastroRepository = cadastroRepository;
        }

        public IActionResult Excluir(string id)
        {
            _cadastroRepository.Excluir(id);

            return RedirectToAction("Index");
        }

        public IActionResult Editar(string id)
        {
            Cadastro cadastro = _cadastroRepository.GetCadastro(id);

            return View(cadastro);
        }

        [HttpPost]
        public IActionResult Editar(Cadastro cadastro)
        {
            _cadastroRepository.Editar(cadastro);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("Usuario") == null)
                return RedirectToAction("Index", "Autenticado");

            if (HttpContext.Session.GetString("Usuario") != "nathankz2@hotmail.com")
                return RedirectToAction("Index", "Home");

            List<Cadastro> cadastros = await _cadastroRepository.GetCadastros();

            return View(cadastros);
        }
    }
}

FinanSmart.WebApp/Controllers/GastosController.cs
using FinanSmart.Dominio.Entities;
using FinanSmart.Dominio.Interface.Repository;
using Microsoft.AspNetCore.Mvc;

namespace FinanSmart.WebApp.Controllers
{
    public class GastosController : Controller
    {
        IGastoRepository _gastoRepository;
        public GastosController(IGastoRepository gastoRepository)
        {
            _gastoRepository = gastoRepository;
        }
        public IActionResult Index()
        {
            string idUsuario = HttpContext.Session.GetString("UsuarioId");
            return View(_gastoRepository.ListarGastos(idUsuario));
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Gasto gasto)
        {
            string idUsuario = HttpContext.Session.GetString("UsuarioId");
            gasto.UsuarioId = idUsuario;
            _gastoRepository.CadastrarGasto(gasto);
            return RedirectToAction("Index");
        }

        public IActionResult Editar(int id)
        {

            return View(_gastoRepository.BuscarGasto(id));
        }

        [HttpPost]
        public IActionResult Editar(Gasto gasto)
        {
            _gastoRepository.EditarGasto(gasto);
            return RedirectToAction("Index");
        }

        public IActionResult Excluir(int id)
        {
            _gastoRepository.ExcluirGasto(_gastoRepository.BuscarGasto(id));
            return RedirectToAction("Index");
        }
    }
}

FinanSmart.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinanSmart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinanSmart.WebApp.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                    <img src="~/img/logo-min.png"/>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    FinanSmart.WebApp
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pagina Inicial</a>
                        </li>

                        @if (Context.Session.GetString("Usuario") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Gastos" asp-action="Index">Gastos</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autenticacao" asp-action="Index">Cadastre-se</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autenticado" asp-action="Index">Logar</a>
                        </li>

                        @if (Context.Session.GetString("Usuario") == "nathankz2@hotmail.com")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cadastros" asp-action="Index">Cadastros</a>
                            </li>
                        }
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @RenderBody()


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>